-- Aggiornamento modalita pagamento fattura da rubrica XML
-- Totale clienti con pagamento: 166

    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Acquamax di Melini Massimigliano')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('ADVITAR SRL')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Agenzia Immobiliare San Marino Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Alleanza Riformista')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Ambeta Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Antincendio Riminese Srl (stabile Organizzazione)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Aqua Viva Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Arch. Amedeo Grandoni (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('AREAUTO SRL')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Armeria Battistini')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Arti Grafiche Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('AscensoriSM Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Associazione Società Sportiva Pennarossa Calcio')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Audiofon San Marino Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Bar Ospedale Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RIBA' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Bartolini Design Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('BDrive Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Berardi Dott. Orietta')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('BERARDI MANUEL RAG. COMM.')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Best Car Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('BLT DIstribution Srl (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Bontempo Patrizia')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Capicchioni Massimo')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Car Service Srl (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Cardelli Alessandro')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Cardinali Marco')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Cardogna Avv. Cecilia')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Cavalli Federico')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Cecchetti Gabriele')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Cellarosi Luca (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Cis-Coop Sistemi Informatici')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Compagnia Arte Spettacolo e Tecnologia Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Contucci Remo')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Coperativa Allevatori C/O Titancoop')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('CORPO DI POLIZIA CIVILE')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Croce Rossa Sammarinese')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RIBA' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Cuckin Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('De Lugii Samuele (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('De Marini Fausto')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Della Valle Nicola')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('DELLA VALLE ORAZIO')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RIBA' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('DOMECAR S.R.L.')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Dr. Marchi Eleonora')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Elettrauto E Ricambi di Cesarini Leonardo')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Enilive Spa')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Ercolani Lorenzo (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Estetikale di Zonzini Alessandra')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('FASHION FORCE SRL')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Federazione Sammarinese Giuoco Calcio')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Federazione Sammarinese Nuoto')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Federazione Tennis RSM')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Federico Filippo Bernardi (p)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Felici Gianluca')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Ferri Ing. Stefano')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Filo D''Erba di Loris Riccardi (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Fonti Luca Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('G.R. Finiture Edili di Giancecchi Roberto')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Garavelli Erika')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Garbellano Omar')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Gattei Ing. Marco')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('GEM BB Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Geom. Casali Matteo')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('GF PROFUMI SRL (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Giancecchi Luca')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Giannini Jean Paul')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Giardi Ivan')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Giorgetti Spa')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Giovagnoli Gerardo')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RIBA' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Glesa Spa')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Grandoni Associati Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Grandoni Real Estate Srl (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Grandoni Simone (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Grassi Ing. Daniel')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Grossi Andrea')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Guerra Stefano')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('I Frutti della Terra di Alan Toccaceli')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('ICAS Spa')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('ICAS Spa (PALA)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Idraulica Mazza di Mazza Andrea')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Idraulica Si.Sa Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Idris di Muscioni Luca')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Il Gommista Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Il Semaforo Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('ING. STEFANO CIACCI (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Ippo srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Iuliano Antonio')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RIBA' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Krea di Agarici Gianfranco e Sandro')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('L''Antenna di Molaroni Guido')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('LA COCCINELLA (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('La Nuova Termoidraulica di Mularoni Enea')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RIBA' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('La Pitagora di Macrelli Dott, Giancarlo')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('LaChiara (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Lancioli Matteo')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Linknet Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Lonfernini Irene (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Loris Zanchi')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Madera s.r.l.')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Maksymenko Oleksandra')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Mancini Valter')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Mas o Mano Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Massimo Molinari')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Massimo Service di Moretti Massimo (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('MCS SRL')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RIBA' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Media Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('MICHELE ROMAGNOLI (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Micronics Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('movimento ideali socialisti (mis)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Muscioni Marco')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('My Bike Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('My Time di Cucchi Emanuela (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Napoleone Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Nutrigea Srl (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Olei Marcello')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Orlando.sm Onoranze Funebri Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Outlet del profumo Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Overview Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Paoloni Sara')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Passepartout Spa (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RIBA' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Passion Car Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Podeschi Fabio')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RIBA' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('PROMOPHARMA SPA')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Righi Giuseppe')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Rondelli Marco')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Rossi Guido')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Rossini Commerce Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Royal Car di Carlini Loris Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RIBA' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('S.J. Escavazioni e Lavori Edili')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('San Marino RTV')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('San Martini Giovanni')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('SASIA DI BOTTINO MARIA TERESA (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Sbc srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RIBA' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('SE.BA.R spa')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Sebron Spa')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Segmento Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Severi Sergio')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Severi Sergio (ULTIMO)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('SHINDAY DI Cecchetti Michele')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Sicurezza e Salute Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Silvagni Ing. Marco (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Solution S.r.l.')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Spray Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Stefanelli Stefano')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('STUDIO BIAGIOLI SRL')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Studio Volpinari')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Tabaccheria Colombo srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Tamagnini Roberto')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Target Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Tecnoedil Fiorentino Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Tecnoproject Srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Telecom italia San Marino Spa')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Telefonia Mobile Sammarinese TMS Spa')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('TIM TRANSITORIO')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Titan Carni Srl (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Toccaceli Mattia (P)')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Ugolini Alessandro')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Urbinati Giugliano')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Vaglio Alberto')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Valtancoli Andrea')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Venerucci Matteo')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'CONTANTI' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Volpinari Arch.Davide')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Wonder Lab di Severi Andrea')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Wonderfood Spa')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Zanotti Stefano ZF')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'BONIFICO' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Zero Mille srl')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RID_SDD' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Zonzini Giacomo')) AND (modalita_pagamento_fattura IS NULL);
    UPDATE clienti SET modalita_pagamento_fattura = 'RIBA' WHERE LOWER(TRIM(nome_ragione_sociale)) = LOWER(TRIM('Zonzini Srl')) AND (modalita_pagamento_fattura IS NULL);
